// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZEGfGEDeNwgEavWZd94EFY2hKH9eO7U',
    appId: '1:411813318199:web:8b54dc9889d49b825039b2',
    messagingSenderId: '411813318199',
    projectId: 'mobilstore-16316',
    authDomain: 'mobilstore-16316.firebaseapp.com',
    databaseURL: 'https://mobilstore-16316-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilstore-16316.appspot.com',
    measurementId: 'G-WVJVND4279',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbMyAJs5qRfCEaUBuchpBthCXsshz1ZY0',
    appId: '1:411813318199:android:9f835201e3a5188f5039b2',
    messagingSenderId: '411813318199',
    projectId: 'mobilstore-16316',
    databaseURL: 'https://mobilstore-16316-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilstore-16316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNSylYoQ5eI5CQcztrG5ycbvoJBYn-wq8',
    appId: '1:411813318199:ios:b81c6b4390aa6e1c5039b2',
    messagingSenderId: '411813318199',
    projectId: 'mobilstore-16316',
    databaseURL: 'https://mobilstore-16316-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilstore-16316.appspot.com',
    iosClientId: '411813318199-2cobvkmvrne2da6dm9rqn675pvi0ag9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNSylYoQ5eI5CQcztrG5ycbvoJBYn-wq8',
    appId: '1:411813318199:ios:fb23ed4be8d4eede5039b2',
    messagingSenderId: '411813318199',
    projectId: 'mobilstore-16316',
    databaseURL: 'https://mobilstore-16316-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilstore-16316.appspot.com',
    iosClientId: '411813318199-g2t62jpdtdtl6sqkqc6hmfat66fm83bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilStore.RunnerTests',
  );
}
