import 'package:mobil_store/models/productModel.dart';

import '../models/categoryModel.dart';

class Lists {
  
  static List<CategoryModel> categories = [
    CategoryModel(
      ID: 1,
      KategortAdi: 'Telefon',
      AKTIF: true,
      TEXTYEDEK1: '1',
      TEXTYEDEK2: '1',
      TEXTYEDEK3: '1',
      SAYISALYEDEK1: 1,
      SAYISALYEDEK2: 1,
    ),
    CategoryModel(
      ID: 2,
      KategortAdi: 'Bilgisayar',
      AKTIF: true,
      TEXTYEDEK1: '1',
      TEXTYEDEK2: '1',
      TEXTYEDEK3: '1',
      SAYISALYEDEK1: 1,
      SAYISALYEDEK2: 1,
    ),
    CategoryModel(
      ID: 3,
      KategortAdi: 'Beyaz Eşya',
      AKTIF: true,
      TEXTYEDEK1: '1',
      TEXTYEDEK2: '1',
      TEXTYEDEK3: '1',
      SAYISALYEDEK1: 1,
      SAYISALYEDEK2: 1,
    ),
  ];
  static List<ProductModel> allProducts = [
    ProductModel(
      ID: 1,
      UrunKodu: '1',
      UrunAdi: 'Telefon',
      UrunAciklama: '1',
      UrunFiyat: 1,
      UrunIndFiyat: 1,
      UrunKDV: '1',
      UrunStokMiktar: 1,
      UrunSatilanMiktar: 1,
      UrunMarka: '1',
      UrunModel: '1',
      TEXTYEDEK1: '1',
      TEXTYEDEK2: '1',
      TEXTYEDEK3: '1',
      SAYISALYEDEK1: 1,
      SAYISALYEDEK2: 1,
      AKTIF: '1',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['1'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 2,
      UrunKodu: '2',
      UrunAdi: 'Bilgisayar',
      UrunAciklama: '2',
      UrunFiyat: 2,
      UrunIndFiyat: 2,
      UrunKDV: '2',
      UrunStokMiktar: 2,
      UrunSatilanMiktar: 2,
      UrunMarka: '2',
      UrunModel: '2',
      TEXTYEDEK1: '2',
      TEXTYEDEK2: '2',
      TEXTYEDEK3: '2',
      SAYISALYEDEK1: 2,
      SAYISALYEDEK2: 2,
      AKTIF: '2',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['2'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
    ProductModel(
      ID: 3,
      UrunKodu: '3',
      UrunAdi: 'Beyaz Eşya',
      UrunAciklama: '3',
      UrunFiyat: 3,
      UrunIndFiyat: 3,
      UrunKDV: '3',
      UrunStokMiktar: 3,
      UrunSatilanMiktar: 3,
      UrunMarka: '3',
      UrunModel: '3',
      TEXTYEDEK1: '3',
      TEXTYEDEK2: '3',
      TEXTYEDEK3: '3',
      SAYISALYEDEK1: 3,
      SAYISALYEDEK2: 3,
      AKTIF: '3',
      GORULDUMU: true,
      FAVORIMI: true,
      SEPETTEMI: true,
      KAMPANYALIMI: true,
      KAMPANYAURUNMUMU: true,
      KAMPANYAAD: ['3'],
      UrunResim: [
        'assets/11.jpg',
        'assets/22.jpg',
        'assets/77.jpg',
      ],
      UrunKategori: [categories[0]],
    ),
  ];
}
