name: mobil_store
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  another_flushbar: ^1.10.29
  another_transformer_page_view: ^2.0.0
  cloud_firestore: ^4.13.2
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.22.0
  firebase_database: ^10.3.5
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.0.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  intl_phone_number_input: ^0.7.2
  mobkit_dashed_border: ^0.0.5
  motion_tab_bar_v2: ^0.3.0
  motion_toast: ^2.7.10
  persistent_bottom_nav_bar: ^5.0.2
  phone_numbers_parser: ^8.0.0
  provider: ^6.0.1
  quiver: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer_animation: ^2.1.0+1
  shrink_sidemenu: ^2.0.0+2-null-safety
  sign_in_button: ^3.0.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mockito: ^5.0.16


flutter:
  uses-material-design: true
  assets:
    - assets/

